var newsData2 = function () {
    var data = [
               {
                   title: "Design",
                   type: "project",
                   date: "1",
                   img: ["App/Modules/Portfolio/Education/Content/bob0488.jpg"],
                   shortTitle: "Design",
                   underTitle: "Skolprojekt",
                   x: 50,
                   y: 150,
                   thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/bob.png",
                   description: "Designprojekt då jag med tre andra planerade och skapade designkonceptet runt en handhållen enhet vi ville uppfinna. Vi skapde Bob, the Book of Books, som var ett digitalt sätt att läsa och lagra böcker (Detta var 2007, långt innan läsplattorna kom ut på marknaden)."
               },
                {
                    title: "3D-Datorgrafik",
                    type: "project",
                    date: "2",
                    img: ["App/Modules/Portfolio/Education/Content/9126_146136472200_3911258_n.jpg"],
                    shortTitle: "3D-Datorgrafik",
                    underTitle: "Skolprojekt",
                    x: 320,
                    y: 160,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/3d2.jpg",
                    description: "Tillsammans med fyra klasskamrater var jag med och skapade dataspelet Volksball, som går ut på att två folkabussar spelar fotboll med en badboll. Spelet är skrivet i C++ med egen fysikmotor och 3D-grafik. Jag arbetade främst i Photoshop och ritade alla texturer, framsidan och hightmapen, men deltogäven i arbetet i 3dStudio Max med bilar och spelplan."
                },
                {
                    title: "Avancerad Bildbehandling",
                    type: "project",
                    date: "4",
                    img: ["App/Modules/Portfolio/Education/Content/im8c.jpg",
                            "App/Modules/Portfolio/Education/Content/prickarochbalkar.png",
                            "App/Modules/Portfolio/Education/Content/boundingbox.png",
                            "App/Modules/Portfolio/Education/Content/klarr.png"],
                    shortTitle: "Bildbehandling",
                    underTitle: "Skolprojekt",
                    x: 480,
                    y: 140,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/abob.png",
                    description: "Skapade i en grupp om tre ett program i  Matlab som, med hjälp av olika bildbehandlingsalgoritmer, tar in en bild på ett notblad och skriver sedan ut noterna i text. Bilderna visar några av stegen som utfördes för att hitta och klassificera noterna."
                },
                {
                    title: "Concept Art",
                    type: "project",
                    date: "2",
                    img: ["App/Modules/Portfolio/Education/Content/39082_432445227200_533537200_5292360_2457477_n.jpg",
                                "App/Modules/Portfolio/Education/Content/flicka.jpg",
                                "App/Modules/Portfolio/Education/Content/37718_428134417200_533537200_5170752_2208684_n.jpg"],
                    shortTitle: "Concept Art",
                    underTitle: "Skolprojekt",
                    x: 550,
                    y: 170,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/concept.png",
                    description: "Målade koncept i Photoshop, bland annat på huvudkaraktären, miljön, vapen och tillbehör, utifrån en given TV-spelsidé. (Sommarkurs på Gotlands universitet)"
                },
                {
                    title: "Bilddatabaser",
                    type: "project",
                    date: "4",
                    img: ["App/Modules/Portfolio/Education/Content/intensity_result.jpg",
                                "App/Modules/Portfolio/Education/Content/query1_facit.jpg",
                                "App/Modules/Portfolio/Education/Content/pojke.jpg"],
                    shortTitle: "Bilddatabaser",
                    underTitle: "Skolprojekt",
                    x: 677,
                    y: 150,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/bdb.png",
                    description: "Tillsammans med två klasskamrater skapade jag program i Matlab som med hjälp av bildbehandlingsalgoritmer, bland annat 3D-histogram, sökte i stora bilddatabaser(5000 bilder stora). Programmen tog in en referebild och spottade ut de 20 bilder som var mest lika referensen. Vi avslutade kursen med att skriva ett program som hittade bilder i bilddatabasen med ansikten på."
                },
                {
                    title: "Agil användbarhetsutveckling för handhållna enheter",
                    type: "project",
                    date: "4",
                    img: ["App/Modules/Portfolio/Education/Content/221790_10150185773562201_533537200_7281160_4615444_n.jpg",
                                "App/Modules/Portfolio/Education/Content/meny.jpeg",
                                "App/Modules/Portfolio/Education/Content/play1.jpeg",
                                "App/Modules/Portfolio/Education/Content/screenshot2_ena.jpg",
                                "App/Modules/Portfolio/Education/Content/screenshot2_andra.jpg"],
                    shortTitle: "Agil",
                    underTitle: "Skolprojekt",
                    x: 750,
                    y: 140,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/agil.jpg",
                    description: "Arbetade i en grupp om åtta enligt Scrum för att skapa Androidspelet ”Peas in war”. Spelet är skrivet i Java och går ut på att två spelare krigar genom att skjuta varandra, alternativt fly med sin lian. Det spelas på två olika androidtelefoner över nätverket. Jag gjorde all grafik till spelet(karaktärer, animationer, menyer och knappar samt spelplanen) i Photoshop och deltogäven i programmeringen."
                },
               {
                   title: "Informationsvisualisering",
                   type: "project",
                   date: "3",
                   img: ["App/Modules/Portfolio/Education/Content/helaprogram.png",
                               "App/Modules/Portfolio/Education/Content/karta.png",
                               "App/Modules/Portfolio/Education/Content/Parallellkoordinate_2004.png",
                               "App/Modules/Portfolio/Education/Content/scatterplot.jpg",
                               "App/Modules/Portfolio/Education/Content/scattermatrix.jpg"],
                   shortTitle: "InfoVis",
                   underTitle: "Skolprojekt",
                   x: 810,
                   y: 130,
                   thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/infoVis.png",
                   description: "Tillsammans med en klasskamrat skapade jag ett program för att visualisera data från statistiska centralbyrån och på så sätt hitta möjliga samband mellan antalet aborter i ett län med andra sociala faktorer. Vi programmerade i C#/.net, i ett framework för informatiovisualisering som heter GAV, och skrev även makro till Excel för att bearbeta de stora mängder data vi hade att arbeta med."
               },
                  {
                      title: "3D-datorgrafik i 3D-Studio Max",
                      type: "project",
                      date: "3",
                      img: ["App/Modules/Portfolio/Education/Content/render01.jpg", "App/Modules/Portfolio/Education/Content/render02.jpg"],
                      shortTitle: "3D-Studio Max",
                      underTitle: "Skolprojekt",
                      x: 820,
                      y: 180,
                      thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/3D_Thumb.png",
                      description: "Lärde mig grunderna i 3D-studio Max där jag bland annat gjorde en delfin. Som miniprojekt skapade jag mitt plugg-”alter ego”, som är byggd av en gitarr, noter, penslar och en basketboll, instängd i en värld av matte. (Sommarkurs på Gotlands universitet)"
                  },
                {
                    title: "Grafisk Design och Kummunikation",
                    type: "project",
                    date: "4",
                    img: ["App/Modules/Portfolio/Education/Content/sidan.jpg"],
                    shortTitle: "Grafisk Design",
                    underTitle: "Skolprojekt",
                    x: 950,
                    y: 160,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/isea.png",
                    description: "Gjorde, tillsammans med två klasskamrater, en grafisk profil för ett fiktivt företag, ISEA, som tillverkar lagerprodukter och planerade även en utförlig marknadsföringsplan för företaget och dess produkter. Jag var grafiskt ansvarig."
                },
                {
                    title: "Teknisk projektledning för Audiovisuell Medieproduktion",
                    type: "project",
                    date: "4",
                    img: ["App/Modules/Portfolio/Education/Content/logga.png",
                            "App/Modules/Portfolio/Education/Content/black.png",
                            "App/Modules/Portfolio/Education/Content/Logga1.jpg",
                            "App/Modules/Portfolio/Education/Content/black1.png",
                            "App/Modules/Portfolio/Education/Content/black8.png",
                            "App/Modules/Portfolio/Education/Content/black2.png",
                            "App/Modules/Portfolio/Education/Content/black6.png",
                            "App/Modules/Portfolio/Education/Content/black3.png"],
                    shortTitle: "Medieproduktion",
                    underTitle: "Skolprojekt",
                    x: 1210,
                    y: 150,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/black.png",
                    description: "Gjorde, med sex klasskamrater, en tre minuter lång informationsfilm för kaffemärket Black Royale. Vi filmade både mot green screen i studio och utomhus. Under inspelningen var jag kameraansvarig och i efterbearbetningen gjorde jag logga, klippte i Premiere och bearbetade film i After Effects."
                },
                     {
                         title: "Examensarbete",
                         type: "project",
                         date: "5",
                         img: ["App/Modules/Portfolio/Education/Content/sida1_1.png",
                             "App/Modules/Portfolio/Education/Content/sida1.png",
                                "App/Modules/Portfolio/Education/Content/Sida2.jpg",
                                "App/Modules/Portfolio/Education/Content/sida2_1.png",
                                "App/Modules/Portfolio/Education/Content/sida2_2.png",
                                "App/Modules/Portfolio/Education/Content/sida2_3.png"],
                         shortTitle: "Examensarbete",
                         underTitle: "Skolprojekt",
                         x: 1320,
                         y: 140,
                         thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/twingly.png",
                         description: "Jag fick i uppdrag av Twingly att skapa en webbaserad applikation för att visualisera bloggstatistik i relation till en specifik blogg. Programmet har som syfte att ge Bloggportalens användare feed-back över bloggens trafik och aktivitet och därmed öka engagemang och länkande hos bloggarna.</br></br> I oktober 2013 belönades mitt arbete med Kaperos stipendium för Sveriges bästa exjobb inom medieteknik.",
                         rapportLink: "http://liu.diva-portal.org/smash/record.jsf?pid=diva2:623128",
                         demoLink: "/bloggportalen-stat/Main/main.html"
                     },
                       {
                           title: "Medietekniks PR-utskott",
                           type: "meriter",
                           date: "1",
                           img: ["App/Modules/Portfolio/Education/Content/medieteknik.jpg"],
                           shortTitle: "PR-utskottet",
                           underTitle: "Övriga meriter",
                           x: 400,
                           y: 80,
                           thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                           description: "Medlem. Hjälpte till i pr-arbetet för Medietekniksektionen bland annat med att informera om event samt att göra reklam för medietekniks sektionsmedlemmar."
                       },
				{
				    title: "Civilingenjörerna i Norrköpings studentförening, 3Cant (08/09)",
				    type: "meriter",
				    date: "2",
				    img: ["App/Modules/Portfolio/Education/Content/IMG_1151.jpg"],
				    shortTitle: "3Cant",
				    underTitle: "Övriga meriter",
				    x: 150,
				    y: 60,
				    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/3Cant.png",
				    description: "Styrelsemedlem, Festerichef-MT. Deltog i mottagningen för nya studenter och anordnade även kravaller, sittningar och andra event under hela studieåret 08/09."
				},
                {
                    title: "Medietekniks Sektionsstyrelse (08/09)",
                    type: "meriter",
                    date: "2",
                    img: ["App/Modules/Portfolio/Education/Content/medieteknik.jpg",
							"App/Modules/Portfolio/Education/Content/P1010309.jpg",
							"App/Modules/Portfolio/Education/Content/tina_stor.jpg"],
                    shortTitle: "MT-styrelsen",
                    underTitle: "Övriga meriter",
                    x: 400,
                    y: 80,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                    description: "Styrelsemedlem, Eventavarig/Festerichef och ordförande i event-utskottet. Anordnade, med hjälp av eventutskottet, event för medietekniks sektionsmedlemmar. Bland annat två event för alla sektionsaktiva och även Medietekniks årliga sittning, MidsommarphesTen. Deltog även i alla de uppdrag som sektionsstyrelsen antog."
                },
                {
                    title: "Medietekniks tjejförening, Mette (08/09)",
                    type: "meriter",
                    date: "2",
                    img: ["App/Modules/Portfolio/Education/Content/Mettemarket.png"],
                    shortTitle: "Mette",
                    underTitle: "Övriga meriter",
                    x: 250,
                    y: 80,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/Mette.png",
                    description: "Styrelsemedlem, informationsansvarig. Deltog i att arrangera event för alla tjejer i medietekniksektionen."
                },
                {
                    title: "Mottagningskommittén för tekniskt basår (09/10)",
                    type: "meriter",
                    date: "3",
                    img: ["App/Modules/Portfolio/Education/Content/torsten.jpg"],
                    shortTitle: "Mottagningskommittén",
                    underTitle: "Övriga meriter",
                    x: 550,
                    y: 80,
                    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/torsten.png",
                    description: "Deltog i mottagningskommittén för tekniskt basår i Norrköping. Anordnade olika event under hela introduktionstiden samt en avslutande sittning. Gruppen deltogäven i mottagningen för alla studenter på tekniska fakulteten som faddrar och skurkerister."
                },
				{
				    title: "Norrlands Nation, Vargtass (09/10)",
				    type: "meriter",
				    date: "3",
				    img: ["App/Modules/Portfolio/Education/Content/affisch2.jpg",
								"App/Modules/Portfolio/Education/Content/502738.jpg",
								"App/Modules/Portfolio/Education/Content/underbart.jpg",
								"App/Modules/Portfolio/Education/Content/vargtassvanster.jpg",
								"App/Modules/Portfolio/Education/Content/vagtasshoger.jpg"
				    ],
				    shortTitle: "Vargtass",
				    underTitle: "Övriga meriter",
				    x: 480,
				    y: 60,
				    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/vargtass.png",
				    description: "Styrelsemedlem, Informations- och tryckavnsarig. Deltog i arrangerandet av en  Åreresa (totalt 150 personer åkte med på resan) och andra event för universitetets största nation, Vargtass. Jag gjordeäven affischer, märke och flyers."
				},
				{
				    title: "Designuppdrag Sunset Sailors",
				    type: "meriter",
				    date: "5",
				    img: ["App/Modules/Portfolio/Education/Content/sun.jpg"],
				    shortTitle: "Designuppdrag",
				    underTitle: "Övriga meriter",
				    x: 942,
				    y: 90,
				    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/sunset.png",
				    description: "Skapade grafiska profilen till bandet Sunset Sailors."
				},
                	{
                	    title: "Revisor för Norrlands Nation, Vargtass",
                	    type: "meriter",
                	    date: "4",
                	    img: ["App/Modules/Portfolio/Education/Content/vagtass.png"],
                	    shortTitle: "Vargtass",
                	    underTitle: "Övriga meriter",
                	    x: 480,
                	    y: 60,
                	    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/vargtass.png",
                	    description: "Revisor för styrelsen 2010-2011."
                	},
                    	{
                    	    title: "IT-supportansvarig, extrajobb på Twingly",
                    	    type: "meriter",
                    	    date: "5",
                    	    img: ["App/Modules/Portfolio/Education/Content/twingly-logotype21.png"],
                    	    shortTitle: "Twingly",
                    	    underTitle: "Övriga meriter",
                    	    x: 480,
                    	    y: 60,
                    	    thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/vargtass.png",
                    	    description: "Extrajobb på Twingly AB i Linköping. Hade ansvar för IT-supporten knuten både till Bloggportalen.se och Twinglys bloggindexeringsverktyg. Detta innebar både support för Twinglys kunder (där ibland Aftonbladet, Adlibris och DN samt olika bloggbevakningsföretag) men även nära kontakt och support med bloggarna. </br></br> Arbetetsuppgifterna bestod oftast av att felsöka pingprocessen (då blogginlägg indexeras), se över bloggarnas RSS-flöden, åtgärda spamrapportering och hjälpa till med bloggarnas användarprofiler på Bloggportalen."
                    	},
                    {
                        title: "Bildbehandling och bildanalys (Matlab)",
                        type: "kurser",
                        date: "3",
                        "underTitle": "Kurs: Medieteknikinriktad",
                        img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                        shortTitle: "Bildbehandling",
                        x: 720,
                        y: 0,
                        thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                        description: "Kursens syfte är att ge en teoretisk och praktisk grund för datoriserad bearbetning och analys av digitala bilder."
                    },
                 {
                     title: "Modelleringsprojekt (Matlab, Simulink)",
                     type: "kurser",
                     date: "3",
                     "underTitle": "Kurs: Medieteknikinriktad",
                     img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                     shortTitle: "Modelleringsprojekt",
                     x: 620,
                     y: 0,
                     thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                     description: "En dynamisk modell ska skapas för ett utvalt projektobjekt. Genom simulering med hjälp av modellen ska objektet studeras dynamiskt. Rapportskrivning och muntlig presentation på svenska."
                 },
                  {
                      title: "Kommunikation och användargränssnitt (Java)",
                      type: "kurser",
                      date: "2",
                      "underTitle": "Kurs: Medieteknikinriktad",
                      img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                      shortTitle: "Användargräsnitt",
                      x: 500,
                      y: 10,
                      thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                      description: "Kursen syftar till att ge studenterna grundläggande kännedom om kognitiva processer och interatkiva datorsystem samt kunskaper om principer, metoder och verktyg för att utveckla datorsystem anpassade till användaren. "
                  },
                   {
                       title: "Vetenskaplig visualisering (C++, Python)",
                       type: "kurser",
                       date: "4",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Vetenskaplig visualisering",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 810,
                       y: 40,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Kursen syftar till att ge fördjupade insikter i metoder för visualisering av vetenskapliga data från experiment och beräkningar samt genom programmeringsövningar belysa dessa metoders möjligheter och begränsningar. "
                   },
                  
                     {
                         title: "VR-teknik (C++)",
                         type: "kurser",
                         date: "4",
                         "underTitle": "Kurs: Medieteknikinriktad",
                         shortTitle: "VR-teknik",
                         img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                         x: 657,
                         y: 10,
                         thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                         description: "Målet med kursenär att studenterna skall få insikt i vad VRär, hur det används och hur det kan implementeras och utnyttjas. De skalläven lära sig analysera behov och utmaningar, och lära sig att tillämpa teorier och principer för att realisera effektiva VR-gränssnitt och -interaktion. "
                     },
                   {
                       title: "Databaser (mySQL)",
                       type: "kurser",
                       date: "2",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Databaser",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 245,
                       y: 0,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Grunderna inom databaser. Databasdesign och SQL-programering."
                   },
                   {
                       title: "Grafisk teknik (Matlab)",
                       type: "kurser",
                       date: "2",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Grafisk teknik",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 110,
                       y: 0,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Informationsteknikens användning vid bildåtergivning och framställning av trycksaker."
                   },
                   {
                       title: "Elektronisk publicering (Html, css, php)",
                       type: "kurser",
                       date: "1",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Elektronisk publicering",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 57,
                       y: 20,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Fokus på tekniker för innehållsutformning inom elektronisk publicering. Grundläggande märkspråk för innehållsutformning. Introduktion till klient-servermodellen och skriptspråk. Introduktion till layout och form inom elektronisk publicering, exempelvis formatmallar."
                   },
                   {
                       title: "Kompression av ljud och bild (Matlab)",
                       type: "kurser",
                       date: "3",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Kompression",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 770,
                       y: 0,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Kursen ska ge kunskap om metoder för komprimering av data, samt hur dessa metoder tillämpas på ljud- och bildsignaler."
                   },
                   {
                       title: "Medierätt",
                       type: "kurser",
                       date: "4",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Medierätt",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 960,
                       y: 40,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Kursen syftar till att den studerande skall tillägna sig goda kunskaper om immaterialrätt, varmed olika former av resultatet av intellektuellt skapande avses. Kursen syftar därmed till att den studerande skall erhålla goda kunskaper om vad som krävs för att lagligt skyddad ensamrätt skall uppnås/föreligga samt att studenten skapar sig förståelse för immaterialrättsliga reglers roll i en marknadsekonomi. Den studerande skalläven förvärva god förmåga att identifiera, analysera och lösa praktiskt inriktade problemställningar inom de angivna rättsområdena."
                   },
                   {
                       title: "Projektledning",
                       type: "kurser",
                       date: "4",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Projektledning",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 900,
                       y: 20,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Ledarskap i projekt. Projekt och organisation. Projektgruppens utveckling. Gruppnormer & grupproller i projekt. Konflikthantering. Motivation & drivkrafter. "
                   },
                   {
                       title: "Datorgrafik",
                       type: "kurser",
                       date: "1",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Datorgrafik",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 190,
                       y: 0,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "2D-grafik: pixelgrafik kontra objektgrafik, primitiver, parametriska och implicita kurvor, transformationer, rendering. Grafikprogrammering i 2D. 3D-grafik: objekt, polygoner, kort om parametriska och implicita ytor, transformationer, projektion, perspektiv, gömda ytor, lokala ljusmodeller. Enklare grafikprogrammering i 3D."
                   },
                   {
                       title: "Videoproduktion",
                       type: "kurser",
                       date: "1",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Videoproduktion",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 0,
                       y: 20,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Efter fullgjord kurs ska kursdeltagaren ha fått en inledande kunskap inom medieområdet. Inom ett område, som studenten själv väljer, erhålls en mer fördjupad kunskap. Efter kursen skall studenten vara bekant med en projektmodell som hjälpmedel och kunna grunderna i enklare rapportskrivning. Vidare skall studenten ha stiftat bekantskap med frågeställningar som rör informationssökning, etik, samt fusk och plagiat."
                   },
                   {
                       title: "Designmönster (Java)",
                       type: "kurser",
                       date: "4",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Designmönster",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 700,
                       y: 20,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Efter kursen ska studenten kunna använda designmönster, det vill säga, utföra lösningar för standardproblem i objektorienterad programvaruutvekling. Studenten skaäven kunna använda programvaruevolutionsmetodik så som refactoring samt beskriva de implementationsmönster (idiom) som kan finnas i ett programspråk."
                   },
                   {
                       title: "Ljudteknik I (Matlab)",
                       type: "kurser",
                       date: "3",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "Ljudteknik",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 730,
                       y: 50,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Grundläggande beskrivning av ljudvågor och fysikaliska fenomen relaterade till dessa. Ljudutberedning och rumsakustik. Psykoakustik: människans uppfattning av ljud. Egenskaper hos några olika ljudalstrare. Ljudmätteknik och elektroniska kretsar relaterade till ljud. Introduktion till digitalt ljud, olika digitala ljudformat och signalbehandling. Grunderna i ljudupptagning och ljudbearbetning."
                   },
                   {
                       title: "Datamodeller för kognitiva processer (Lisp)",
                       type: "kurser",
                       date: "3",
                       "underTitle": "Kurs: Medieteknikinriktad",
                       shortTitle: "AI",
                       img: ["App/Modules/Portfolio/Education/Content/mt_thumb.png"],
                       x: 850,
                       y: 10,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/mt.png",
                       description: "Grunder, tekniker och begrepp inom AI-programering."
                   },
                   {
                       title: "Programkotruktion (Ada)",
                       type: "kurser",
                       date: "1",
                       "underTitle": "Kurs: Programering",
                       shortTitle: "Programkotruktion",
                       img: ["App/Modules/Portfolio/Education/Content/computer_icon.png"],
                       x: 30,
                       y: 200,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/computer_icon.png",
                       description: "Kursen skall ge grundläggande kunskaper om hur man konstruerar program i ett högnivåspråk, ada."
                   },
                   {
                       title: "Objektorienterad programmering (Java)",
                       type: "kurser",
                       date: "1",
                       "underTitle": "Kurs: Programering",
                       shortTitle: "Java",
                       img: ["App/Modules/Portfolio/Education/Content/computer_icon.png"],
                       x: 155,
                       y: 250,
                       thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/computer_icon.png",
                       description: "Kursen ska ge kunskaper om objektorienterad programutveckling och programmering i ett objektorienterat programspråk, Java."
                   },
                    {
                        title: "C# och .net",
                        type: "kurser",
                        date: "5",
                        "underTitle": "Kurs: Programering",
                        shortTitle: "C# ",
                        img: ["App/Modules/Portfolio/Education/Content/computer_icon.png"],
                        x: 1100,
                        y: 240,
                        thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/computer_icon.png",
                        description: "Kursens målär att ge en bra försåelse och grund inom C#/.net."
                    },
                     {
                         title: "Programmering i C++",
                         type: "kurser",
                         date: "2",
                         "underTitle": "Kurs: Programering",
                         shortTitle: "C++ ",
                         img: ["App/Modules/Portfolio/Education/Content/computer_icon.png"],
                         x: 510,
                         y: 250,
                         thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/computer_icon.png",
                         description: "Kursens syfteär att ge kunskaper i att använda programspråket C++ för att utveckla program. "
                     },
                      {
                          title: "Matematisk grundkurs",
                          type: "kurser",
                          date: "1",
                          "underTitle": "Kurs: Matematik",
                          shortTitle: "Matematisk grundkurs",
                          img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                          x: 80,
                          y: 200,
                          thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                          description: "Kursen syftar till att bidra till en positiv start på universitetsstudierna, både då det gäller en social tillhörighet samt att få en repetition av matematik från tidigare studier. Dessutom skall några matematiska begrepp, som för mångaär nya, introduceras."
                      },
                        {
                            title: "Linjär algebra",
                            type: "kurser",
                            date: "1",
                            "underTitle": "Kurs: Matematik",
                            shortTitle: "Linjär algebra",
                            img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                            x: 90,
                            y: 250,
                            thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                            description: "Att ge sammanhållen begreppsram för geometrisk och algebraisk teknik med tillämpningar inom analys, datorgrafik, elektroteknik, reglerteknik, linjär optimering m fl.ämnen. Vidare ingår att utveckla förmågan att använda det matematiska språket, skriftligt och muntligt."
                        },
                         {
                             title: "Analys I",
                             type: "kurser",
                             date: "1",
                             "underTitle": "Kurs: Matematik",
                             shortTitle: "Analys I",
                             img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                             x: 220,
                             y: 240,
                             thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                             description: "Att du som student skall tillägna dig den förtrogenhet med matematiska begrepp, resonemang och samband som ryms inom envariabelsanalys samt den färdighet i kalkyl och problemlösning som behövs för de fortsatta studierna."
                         },
                         {
                             title: "Analys II",
                             type: "kurser",
                             date: "1",
                             "underTitle": "Kurs: Matematik",
                             shortTitle: "Analys II",
                             img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                             x: 260,
                             y: 210,
                             thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                             description: "Att du som student skall tillägna dig den förtrogenhet med matematiska begrepp, resonemang och samband som ryms inom envariabelsanalys samt den färdighet i kalkyl och problemlösning som behövs för de fortsatta studierna. "
                         },
                         {
                             title: "Analys III",
                             type: "kurser",
                             date: "2",
                             "underTitle": "Kurs: Matematik",
                             shortTitle: "Analys III",
                             img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                             x: 350,
                             y: 240,
                             thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                             description: "Kursen bygger på kursen i Analys I-II. Följaktligenär målen likartade: att ge de studerande förståelse för matematiska begrepp och förtrogenhet med matematiska metoder för funktioner av flera variabler som uppstår i alla grenar av fysik och teknik."
                         },
                         {
                             title: "Vektoranalys",
                             type: "kurser",
                             date: "2",
                             "underTitle": "Kurs: Matematik",
                             shortTitle: "Vektoranalys",
                             img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                             x: 380,
                             y: 180,
                             thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                             description: "Kursen bygger på kursen i flervariabelanalys. Följaktligenär målen likartade: att ge de studerande förståelse för matematiska begrepp och förtrogenhet med matematiska metoder för vektorfält som uppstår i alla grenar av fysik och teknik."
                         },
                         {
                             title: "Matematisk statistik",
                             type: "kurser",
                             date: "3",
                             "underTitle": "Kurs: Matematik",
                             shortTitle: "Matematisk statistik",
                             img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                             x: 450,
                             y: 200,
                             thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                             description: "Kursen avser att lära den studerande förstå och utnyttja grundläggande sannolikhetslära och statistik, dvs teorin för försök som påverkas av slumpmässiga faktorer. Kursen inriktas speciellt på sådana grundläggande kunskaper som krävs för tillämpningar inom teknik, ekonomi och naturvetenskap."
                         },
                        {
                            title: "Tillämpad Transformteori",
                            type: "kurser",
                            date: "2",
                            "underTitle": "Kurs: Matematik",
                            shortTitle: "Transformteori",
                            img: ["App/Modules/Portfolio/Education/Content/matte.png"],
                            x: 410,
                            y: 220,
                            thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/thumb.png",
                            description: "Kursen skall ge de matematiska grunderna för de transformmetoder som används i kretsteori, reglerteori, signaler och system, bildbehandling och produktionsekonomi. "
                        },
                        {
                            title: "Signaler och system",
                            type: "kurser",
                            date: "2",
                            "underTitle": "Kurs: Civilingenjörsinriktad",
                            shortTitle: "Signaler och system",
                            img: ["App/Modules/Portfolio/Education/Content/ciin.png"],
                            x: 650,
                            y: 250,
                            thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/ciin.png",
                            description: "Grundläggande signaler och deras egenskaper, LTI-system, Fouriertransformen och frekvensanalys, Samplingsvillkor och tidsdiskreta signaler, Laplacetransformen och systemanalys, Z-transformen för samplade signaler och system, Digitala filter, Adaptiva filter."
                        },
                        {
                            title: "Modellbygge och simulering",
                            type: "kurser",
                            date: "3",
                            "underTitle": "Kurs: Civilingenjörsinriktad",
                            shortTitle: "Simulering",
                            img: ["App/Modules/Portfolio/Education/Content/ciin.png"],
                            x: 700,
                            y: 250,
                            thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/ciin.png",
                            description: "Kursen skall ge kunskaper om metoder och principer att bygga matematiska modeller för dynamiska system (dvs system som beskrivs med hjälp av differential och/eller differensekvationer). Kursen skall också ge kunskaper om hur modellernas egenskaper studeras genom simulering."
                        },
                        {
                            title: "Reglerteknik",
                            type: "kurser",
                            date: "3",
                            "underTitle": "Kurs: Civilingenjörsinriktad",
                            shortTitle: "Reglerteknik",
                            img: ["App/Modules/Portfolio/Education/Content/ciin.png"],
                            x: 570,
                            y: 230,
                            thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/ciin.png",
                            description: "Kursen skall ge förståelse för dynamiska system och kunskaper om grundläggande metoder för att analysera och dimensionera återkopplade reglersystem."
                        },
                    {
                        title: "Industriell ekonomi",
                        type: "kurser",
                        date: "5",
                        "underTitle": "Kurs: Civilingenjörsinriktad",
                        shortTitle: "Industriell ekonomi",
                        img: ["App/Modules/Portfolio/Education/Content/ciin.png"],
                        x: 1180,
                        y: 220,
                        thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/ciin.png",
                        description: "Kursen avser att ge de studerande en orientering i de sammanhang företag verkar."
                    },
                    {
                        title: "Retorik",
                        type: "kurser",
                        date: "5",
                        underTitle: "Kurs: Civilingenjörsinriktad",
                        shortTitle: "Retorik",
                        img: ["App/Modules/Portfolio/Education/Content/ciin.png"],
                        x: 1250,
                        y: 250,
                        thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/ciin.png",
                        description: "Föreläsningar i retorikens teori och retorisk analys, med aktuella exempel. Seminarier kring retorikens genrer och dess klassiska och moderna uttrycksformer. Den studerande genomför egna presentationer, analyser samt skriver texter där retorikens olika grepp och stilmedel används."
                    },
                    {
                        title: "Tillämpad matematik i teknik och naturvetenskap",
                        type: "kurser",
                        date: "1",
                        "underTitle": "Kurs: Civilingenjörsinriktad",
                        shortTitle: "Matlab info",
                        img: ["App/Modules/Portfolio/Education/Content/ciin.png"],
                        x: 340,
                        y: 250,
                        thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/ciin.png",
                        description: "Kursen avser att utgöra en brygga mellan de grundläggande matematikkurserna och kurser inom teknik och naturvetenskap. Genom att använda beräkningshjälpmedel som Matlab kan mer realistiska problem studeras och studenterna skall vänja sig vid att naturligt använda det språk som matematikstudierna ger dem för att tala om tillämpade problemställningar."
                    },
                    {
                        title: "Mekanik- och vågfysik",
                        type: "kurser",
                        date: "2",
                        "underTitle": "Kurs: Civilingenjörsinriktad",
                        shortTitle: "Fysik",
                        img: ["App/Modules/Portfolio/Education/Content/ciin.png"],
                        x: 300,
                        y: 250,
                        thumbNail: "App/Modules/Portfolio/Education/Content/ThumbNails/ciin.png",
                        description: "Kursen skall ge grundläggande kunskaper inom några centrala delar av den klassiska fysiken samt kännedom om viktiga tillämpningar. Laborationsdelen skall ge erfarenhet av att planera,utföra och redovisa experiment. "
                    }
    ];
    return data;
}